### ISSUE TITLE
Ability to Play Any Audio File in SFU

### ISSUE THREAD

**Issue by moksh-samespace** [inlivedev/sfu#18]
It would be great to have the ability to play any audio file to participant. This would allow us to inject pre-recorded messages, alerts, or background music into calls.

 Thank you for the fantastic work on this project and for making it open source. It’s been invaluable to our work.

**Comment by tyohan** [comment]
Thank you for the suggestion but it seems it out of scope. You need to develop a client that publish a track to this SFU. The SFU basically will only receive stream input and forward it.

**Comment by Manjit2003** [comment]
Hey, @tyohan I am also stuck on the same issue. Basically what I want to achieve is sending the track only to a particular user instead of all the clients. Can you guide me how can this be achieved? 

Thanks

**Comment by tyohan** [comment]
Do you mean send the track from a client to another client through this SFU? If yes, a way to do it is by utilizing room datachannel. 
1. Create a data channel and make sure the all clients listen to it.
2. When you publish a track by add a transceiver to peer connection instance and negotiate it, the SFU should trigger `client.OnTrackAdded()` event as mentioned [here](https://github.com/inlivedev/sfu?tab=readme-ov-file#publish-and-subscribe-tracks). From that event you will find the `trackid` of added track.
3. Send the trackid to the client who will receive it through datachannel before call `client. SetTracksSourceType()` because once you call it it will trigger `client.OnTrackAvailable()` on other clients. You can also wait the receiver client to confirm that it receive the message from datachannel by sending back a confirmation message.
4. When the receiver client receive `client.OnTrackAvailable()` event, it should check if the trackid from that event is the same one with the trackid it received from datachannel. If yes, then the client must call `client.SubscribeTracks()` to receive the track.

**Comment by Manjit2003** [comment]
Thank you @/tyohan for the suggestions! Just in case you have any code snippet for this available can you share it? Like for playing audio to a client, we will have to add another client in the room right?

**Comment by tyohan** [comment]
I don't have my own snippet or example but this Pion [play from disk example](https://github.com/pion/webrtc/tree/master/examples/play-from-disk) might can help you.
